/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yusra Fahim
 */
public class Restaurant extends javax.swing.JFrame {
Connection con;
ResultSet rs;
Statement ps;
    /**
     * Creates new form Restaurant
     */
    public Restaurant() {
        initComponents();
         try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con=DriverManager.getConnection("jdbc:odbc:ResturantDSN");
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Data Not Connected "+ex);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Fastfood = new javax.swing.JComboBox();
        Serving = new javax.swing.JComboBox();
        Quantity = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Chips_size = new javax.swing.JComboBox();
        No_of_chips = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Drink_type = new javax.swing.JComboBox();
        No_of_drinks = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Cash_given = new javax.swing.JTextField();
        Total_amount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Customername = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Algerian", 0, 14))); // NOI18N
        jPanel2.setToolTipText("");

        jTextField2.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Select Your Food");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        jLabel1.setText("Fast Food:");

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel3.setText("Serving:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Quantity:");

        Fastfood.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Pizza", "Chicken Burger", "Zinger Burger", "Chcken Roll" }));
        Fastfood.setToolTipText("1 2 3");
        Fastfood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FastfoodActionPerformed(evt);
            }
        });

        Serving.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4" }));

        Quantity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Fastfood, 0, 1, Short.MAX_VALUE)
                                .addComponent(Quantity, 0, 93, Short.MAX_VALUE))
                            .addComponent(Serving, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fastfood, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Serving, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(Quantity, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jTextField3.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("CHIPS");

        jLabel4.setText("Chips Size:");

        jLabel5.setText("No. Of Chips:");

        Chips_size.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Small", "Medium", "Large" }));

        No_of_chips.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Chips_size, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(No_of_chips, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Chips_size, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(No_of_chips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jTextField4.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("DRINKS");

        jLabel6.setText("Drink Type:");

        jLabel7.setText("No. Of Drinks");

        Drink_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Pepsi ", "Coca Cola", "7up", "Dew", "Marinda" }));

        No_of_drinks.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Drink_type, 0, 321, Short.MAX_VALUE)
                            .addComponent(No_of_drinks, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Drink_type, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(No_of_drinks)
                        .addGap(4, 4, 4))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ORDER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(204, 204, 255))); // NOI18N

        jLabel9.setText("Cash Given:");

        jLabel10.setText("Total Amount:");

        jButton1.setText("Clear Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Submit Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cash_given)
                            .addComponent(Total_amount)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cash_given, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Total_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/thanksgiving-portion-1.jpg"))); // NOI18N

        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Customer Name:");
        jLabel11.setOpaque(true);

        Customername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomernameActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("                                                                              Food Order");
        jLabel13.setOpaque(true);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/3.jpg"))); // NOI18N

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(Customername))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(147, 147, 147)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Customername, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(365, 365, 365))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(389, 389, 389))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FastfoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FastfoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FastfoodActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Fastfood.setSelectedItem("None");
Serving.setSelectedItem("0");
Quantity.setSelectedItem("0");
Chips_size.setSelectedItem("None");
No_of_chips.setSelectedItem("0");
Drink_type.setSelectedItem("None");
No_of_drinks.setSelectedItem("0");
Cash_given.setText("");
Total_amount.setText("");
Customername.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{
    int amount=0;
    int amount1=0;
    int amount2=0;
    int amount3=0;
    if(Fastfood.getSelectedItem().equals("Pizza")){
        amount1=750;
    if(Quantity.getSelectedItem().equals("1")){
    amount1*=1;
    }
    else if(Quantity.getSelectedItem().equals("2")){
    amount1*=2;
    }
    else if(Quantity.getSelectedItem().equals("3")){
    amount1*=3;
    }
    else if(Quantity.getSelectedItem().equals("4")){
    amount1*=4;
    }
    else if(Quantity.getSelectedItem().equals("5")){
    amount1*=5;
    }
    else if(Quantity.getSelectedItem().equals("6")){
    amount1*=6;
    }
    else if(Quantity.getSelectedItem().equals("7")){
    amount1*=7;
    }
    else if(Quantity.getSelectedItem().equals("8")){
    amount1*=8;
    }
    else if(Quantity.getSelectedItem().equals("9")){
    amount1*=9;
    }
    else if(Quantity.getSelectedItem().equals("10")){
    amount1*=10;
    }
    }
    else if(Fastfood.getSelectedItem().equals("Chicken Burger")){
    amount1=200;
    if(Quantity.getSelectedItem().equals("1")){
    amount1*=1;
    }
    else if(Quantity.getSelectedItem().equals("2")){
    amount1*=2;
    }
    else if(Quantity.getSelectedItem().equals("3")){
    amount1*=3;
    }
    else if(Quantity.getSelectedItem().equals("4")){
    amount1*=4;
    }
    else if(Quantity.getSelectedItem().equals("5")){
    amount1*=5;
    }
    else if(Quantity.getSelectedItem().equals("6")){
    amount1*=6;
    }
    else if(Quantity.getSelectedItem().equals("7")){
    amount1*=7;
    }
    else if(Quantity.getSelectedItem().equals("8")){
    amount1*=8;
    }
    else if(Quantity.getSelectedItem().equals("9")){
    amount1*=9;
    }
    else if(Quantity.getSelectedItem().equals("10")){
    amount1*=10;
    }
    }
    else if(Fastfood.getSelectedItem().equals("Zinger Burger")){
    amount1=250;
    if(Quantity.getSelectedItem().equals("1")){
    amount1*=1;
    }
    else if(Quantity.getSelectedItem().equals("2")){
    amount1*=2;
    }
    else if(Quantity.getSelectedItem().equals("3")){
    amount1*=3;
    }
    else if(Quantity.getSelectedItem().equals("4")){
    amount1*=4;
    }
    else if(Quantity.getSelectedItem().equals("5")){
    amount1*=5;
    }
    else if(Quantity.getSelectedItem().equals("6")){
    amount1*=6;
    }
    else if(Quantity.getSelectedItem().equals("7")){
    amount1*=7;
    }
    else if(Quantity.getSelectedItem().equals("8")){
    amount1*=8;
    }
    else if(Quantity.getSelectedItem().equals("9")){
    amount1*=9;
    }
    else if(Quantity.getSelectedItem().equals("10")){
    amount1*=10;
    }
    }
    else if(Fastfood.getSelectedItem().equals("Chcken Roll")){
    amount1=80;
    if(Quantity.getSelectedItem().equals("1")){
    amount1*=1;
    }
    else if(Quantity.getSelectedItem().equals("2")){
    amount1*=2;
    }
    else if(Quantity.getSelectedItem().equals("3")){
    amount1*=3;
    }
    else if(Quantity.getSelectedItem().equals("4")){
    amount1*=4;
    }
    else if(Quantity.getSelectedItem().equals("5")){
    amount1*=5;
    }
    else if(Quantity.getSelectedItem().equals("6")){
    amount1*=6;
    }
    else if(Quantity.getSelectedItem().equals("7")){
    amount1*=7;
    }
    else if(Quantity.getSelectedItem().equals("8")){
    amount1*=8;
    }
    else if(Quantity.getSelectedItem().equals("9")){
    amount1*=9;
    }
    else if(Quantity.getSelectedItem().equals("10")){
    amount1*=10;
    }
    }
    if(Chips_size.getSelectedItem().equals("Small")){
        amount2=50;
        if(No_of_chips.getSelectedItem().equals("1")){
    amount2*=1;
    }
    else if(No_of_chips.getSelectedItem().equals("2")){
    amount2*=2;
    }
    else if(No_of_chips.getSelectedItem().equals("3")){
    amount2*=3;
    }
    else if(No_of_chips.getSelectedItem().equals("4")){
    amount2*=4;
    }
    else if(No_of_chips.getSelectedItem().equals("5")){
    amount2*=5;
    }
    else if(No_of_chips.getSelectedItem().equals("6")){
    amount2*=6;
    }
    else if(No_of_chips.getSelectedItem().equals("7")){
    amount2*=7;
    }
    else if(No_of_chips.getSelectedItem().equals("8")){
    amount2*=8;
    }
    else if(No_of_chips.getSelectedItem().equals("9")){
    amount2*=9;
    }
    else if(No_of_chips.getSelectedItem().equals("10")){
    amount2*=10;
    }
    }
    else if(Chips_size.getSelectedItem().equals("Medium")){
        amount2=100;
        if(No_of_chips.getSelectedItem().equals("1")){
    amount2*=1;
    }
    else if(No_of_chips.getSelectedItem().equals("2")){
    amount2*=2;
    }
    else if(No_of_chips.getSelectedItem().equals("3")){
    amount2*=3;
    }
    else if(No_of_chips.getSelectedItem().equals("4")){
    amount2*=4;
    }
    else if(No_of_chips.getSelectedItem().equals("5")){
    amount2*=5;
    }
    else if(No_of_chips.getSelectedItem().equals("6")){
    amount2*=6;
    }
    else if(No_of_chips.getSelectedItem().equals("7")){
    amount2*=7;
    }
    else if(No_of_chips.getSelectedItem().equals("8")){
    amount2*=8;
    }
    else if(No_of_chips.getSelectedItem().equals("9")){
    amount2*=9;
    }
    else if(No_of_chips.getSelectedItem().equals("10")){
    amount2*=10;
    }
    }
    else if(Chips_size.getSelectedItem().equals("Large")){
        amount2=200;
        if(No_of_chips.getSelectedItem().equals("1")){
    amount2*=1;
    }
    else if(No_of_chips.getSelectedItem().equals("2")){
    amount2*=2;
    }
    else if(No_of_chips.getSelectedItem().equals("3")){
    amount2*=3;
    }
    else if(No_of_chips.getSelectedItem().equals("4")){
    amount2*=4;
    }
    else if(No_of_chips.getSelectedItem().equals("5")){
    amount2*=5;
    }
    else if(No_of_chips.getSelectedItem().equals("6")){
    amount2*=6;
    }
    else if(No_of_chips.getSelectedItem().equals("7")){
    amount2*=7;
    }
    else if(No_of_chips.getSelectedItem().equals("8")){
    amount2*=8;
    }
    else if(No_of_chips.getSelectedItem().equals("9")){
    amount2*=9;
    }
    else if(No_of_chips.getSelectedItem().equals("10")){
    amount2*=10;
    }
    }
    if(No_of_chips.getSelectedItem().equals("1")){
    amount2*=1;
    }
    else if(No_of_chips.getSelectedItem().equals("2")){
    amount2*=2;
    }
    else if(No_of_chips.getSelectedItem().equals("3")){
    amount2*=3;
    }
    else if(No_of_chips.getSelectedItem().equals("4")){
    amount2*=4;
    }
    else if(No_of_chips.getSelectedItem().equals("5")){
    amount2*=5;
    }
    else if(No_of_chips.getSelectedItem().equals("6")){
    amount2*=6;
    }
    else if(No_of_chips.getSelectedItem().equals("7")){
    amount2*=7;
    }
    else if(No_of_chips.getSelectedItem().equals("8")){
    amount2*=8;
    }
    else if(No_of_chips.getSelectedItem().equals("9")){
    amount2*=9;
    }
    else if(No_of_chips.getSelectedItem().equals("10")){
    amount2*=10;
    }
    amount3=30;
    if(No_of_drinks.getSelectedItem().equals("1")){
    amount3*=1;
    }
    else if(No_of_drinks.getSelectedItem().equals("2")){
    amount3*=2;
    }
    else if(No_of_drinks.getSelectedItem().equals("3")){
    amount3*=3;
    }
    else if(No_of_drinks.getSelectedItem().equals("4")){
    amount3*=4;
    }
    else if(No_of_drinks.getSelectedItem().equals("5")){
    amount3*=5;
    }
    else if(No_of_drinks.getSelectedItem().equals("6")){
    amount3*=6;
    }
    else if(No_of_drinks.getSelectedItem().equals("7")){
    amount3*=7;
    }
    else if(No_of_drinks.getSelectedItem().equals("8")){
    amount3*=8;
    }
    else if(No_of_drinks.getSelectedItem().equals("9")){
    amount3*=9;
    }
    else if(No_of_drinks.getSelectedItem().equals("10")){
    amount3*=10;
    }
    
    amount=amount1+amount2+amount3;
    Total_amount.setText(Integer.toString(amount));
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            String url  = "jdbc:odbc:ResturantDSN";
            
            con = DriverManager.getConnection(url);
            ps =  con.createStatement();
            String query=("INSERT INTO Detail (Customer_name,Fastfood,Serving,Quantity,No_of_chips,Chips_size,No_of_drinks,Drink_type,Total_amount) VALUES('"+Customername.getText()+"','"+Fastfood.getSelectedItem().toString()+"',"+Integer.parseInt(Serving.getSelectedItem().toString())+","+Integer.parseInt(Quantity.getSelectedItem().toString())+","+Integer.parseInt(No_of_chips.getSelectedItem().toString())+",'"+Chips_size.getSelectedItem().toString()+"',"+Integer.parseInt(No_of_drinks.getSelectedItem().toString())+",'"+Drink_type.getSelectedItem().toString()+"',"+Total_amount.getText()+")");
       ps.executeUpdate(query);
              
       ps.close();
       JOptionPane.showMessageDialog(this, "Order Placed.");
       }catch(Exception e){
       JOptionPane.showMessageDialog(this, "Data not inserted"+e);
       }       
              // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String b=Customername.getText();
        
        this.dispose();
        Invoice a= new Invoice(b);
       a.setVisible(true);
       
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CustomernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomernameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.dispose();
First a= new First();
a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cash_given;
    private javax.swing.JComboBox Chips_size;
    private javax.swing.JTextField Customername;
    private javax.swing.JComboBox Drink_type;
    private javax.swing.JComboBox Fastfood;
    private javax.swing.JComboBox No_of_chips;
    private javax.swing.JComboBox No_of_drinks;
    private javax.swing.JComboBox Quantity;
    private javax.swing.JComboBox Serving;
    private javax.swing.JTextField Total_amount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
